load('humanScore.mat')
humanScore = [mean(id1) mean(id2) mean(ood1) 0.7966 (0.8776*35+0.8677*35+0.8870*25)/95 0.8700 (0.9475+0.9407)/2];
load('modelScore.mat')
modelScore = [mean(id1) mean(id2) mean(ood1) mean(ood2) mean([ood3,ood4,ood5]) mean(ood6) mean([ood7, ood8])];
load('baselineScore.mat')
baselineScore = [mean(id1) mean(id2) mean(ood1) mean(ood2) mean([ood3,ood4,ood5]) mean(ood6) mean([ood7, ood8])];
% Initialize data points
% humanScore = [5 3 9 1 2 3 4]./10; % fake data
% modelScore = [5 8 7 2 9 5 6]./10; % fake data
% baslineScore = [8 2 1 4 6 7 8]./10; % fake data
P = [humanScore; modelScore; baselineScore];
legends = {'Humans', 'VF(ours)', 'FeatOnly'};
linecolors = [1, 0, 0; 0, 0, 1; 0.3, 0.3, 0.3];
labels = {'UnValEqPre', 'UnValUnPre', 'EqValUnPre', 'UTargets', 'UValues', 'UItemNum', 'USetSize'};

% Spider plot
figure;
figure.Position = [0, 0, 800, 600];
figure.InnerPosition = [0, 0, 800, 600];
spider_plot(P,...
    'AxesLimits', [0,0,0,0,0,0,0; 1,1,1,1,1,1,1],... % [min axes limits; max axes limits]
    'AxesPrecision', 1,...
    'AxesInterval', 2,...
    'AxesDisplay', 'one',...
    'AxesLabels', labels,...
    'Color', linecolors,...
    'LineStyle', {'-', '-', ':'},...
    'LineWidth', [4, 4, 4],...
    'Marker', {'none', 'none', 'none'},...
    'AxesFont', 'Arial',...
    'LabelFont', 'Arial',...
    'AxesFontSize', 18,...
    'LabelFontSize', 24,...
    'AxesLabelsEdge', 'none',...
    'AxesOffset', 0,...
    'MinorGrid', 'on',...
    'MinorGridInterval', 2,...
    'PlotVisible', 'on',...
    'AxesRadialLineWidth', 1,...
    'AxesWebLineWidth', 1,...
    'AxesLabelsOffset', 0.15,...
    'AxesVertAlign', 'cap');

% Legend settings
legend(legends, 'FontName', 'Arial', 'FontSize', 18, 'Location', 'southoutside', 'Box', 'off', 'FontWeight', 'bold', 'Orientation', 'horizontal');